version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuetify
    versions:
    - 2.4.10
    - 2.4.4
    - 2.4.7
    - 2.4.9
  - dependency-name: markdown-it
    versions:
    - 12.0.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.2
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.2.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.3.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
